# Generated by Django 4.0.4 on 2022-05-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Company',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('is_archived', models.BooleanField(blank=True, default=False, verbose_name='Is archived')),
				('slug', models.SlugField(unique=True, verbose_name='Slug')),
			],
			options={
				'verbose_name': 'Company',
				'verbose_name_plural': 'Companies',
			},
		),
		migrations.CreateModel(
			name='CompanyVersion',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100, verbose_name='Company name')),
				('address', models.TextField(verbose_name='Address')),
				('ico', models.CharField(blank=True, max_length=20, verbose_name='IČO')),
				('dic', models.CharField(blank=True, max_length=20, verbose_name='DIČ')),
				('ic_dph', models.CharField(blank=True, max_length=20, verbose_name='IČ DPH')),
				('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Bank account number')),
				('bank_code', models.CharField(blank=True, max_length=20, verbose_name='Bank code')),
				('swift', models.CharField(blank=True, max_length=20, verbose_name='Swift code')),
				('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
				('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company', verbose_name='Company')),
			],
			options={
				'verbose_name': 'Company version',
				'verbose_name_plural': 'Company versions',
			},
		),
		migrations.CreateModel(
			name='Invoice',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('date_created', models.DateField(editable=False)),
				('number', models.CharField(max_length=20, unique=True, verbose_name='Number')),
				('due', models.DateField(verbose_name='Due date')),
				('delivery', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
				('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='web.companyversion', verbose_name='Company')),
				('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to='web.companyversion', verbose_name='Issuer')),
			],
			options={
				'verbose_name': 'Invoice',
				'verbose_name_plural': 'Invoices',
			},
		),
		migrations.CreateModel(
			name='Item',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('item', models.CharField(max_length=100, verbose_name='Item')),
				('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
				('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.invoice', verbose_name='Invoice')),
			],
			options={
				'verbose_name': 'Invoice item',
				'verbose_name_plural': 'Invoice items',
				'ordering': ('pk',),
			},
		),
	]
