# Generated by Django 4.1.7 on 2023-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('web', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='item',
			name='quantity',
			field=models.DecimalField(decimal_places=0, default=1, max_digits=20, verbose_name='Quantity'),
		),
		migrations.AddField(
			model_name='item',
			name='unit',
			field=models.CharField(blank=True, default='', max_length=20, verbose_name='Unit'),
		),
	]
