# Generated by Django 4.1.7 on 2023-05-30 16:21

from django.db import migrations, models
from django.db.models import F


def set_unit_price(apps, schema_editor):
	Item = apps.get_model('web.Item')
	db_alias = schema_editor.connection.alias
	Item.objects.using(db_alias).update(unit_price=F('price') / F('quantity'))


class Migration(migrations.Migration):

	dependencies = [
		('web', '0002_item_quantity_item_unit'),
	]

	operations = [
		migrations.AddField(
			model_name='item',
			name='unit_price',
			field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Unit price'),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='item',
			name='quantity',
			field=models.DecimalField(decimal_places=5, default=1, max_digits=20, verbose_name='Quantity'),
		),
		migrations.RunPython(set_unit_price, migrations.RunPython.noop)
	]
